name: Bazel CI
on:
<<<<<<< HEAD
  push:
    branches: [gz-plugin3, main]
  pull_request:
    branches: [gz-plugin3, main]
=======
  pull_request:
  push:
    branches:
      - 'gz-plugin[1-9]?[0-9]'
      - 'main'
>>>>>>> 250fd7c ([bazel/infra] CI updates (#193))

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v7.2.3
    with:
      folders: |
        [
          ".",
        ]
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false},
        ]
      exclude_windows: true
      bazel_test_command: "bazel test --test_output=errors //..."
